#!/bin/bash

#basically copied from commander's main.py in this directory by Uruk
#(to Hochkomma or not to Hochkomma that's the question)

CLOCK_IP="192.168.84.49"

declare -A texts
texts[0]="yolo"
texts[1]="oida"
texts[2]="test"
texts[3]="1337"


# longtext="das passwort ist sicher nicht 1234"
longtext="CYBER"
len=$(echo $longtext | wc -c)
#add some padding spaces
longtext="    "$longtext"    "
#echo $len

trap "curl -sS 'http://'${CLOCK_IP}'/api/v1/set?overrideDigits='" EXIT


i=0;

while true; do

	curstr="${longtext:i:4}"

	#echo "$curstr"
	curstr=$(echo "$curstr" | sed 's/\ /%20/g')
	#echo "$curstr"

	#curl -sS 'http://'${CLOCK_IP}'/api/v1/set?overrideDigits='${texts[$i]} >/dev/null
        before=$(date +%s%N)
	curl -sS 'http://'${CLOCK_IP}'/api/v1/set?overrideDigits='"${curstr}" >/dev/null
	after=$(date +%s%N)
	echo "Diff=$((after-before))"
	interval=0.5
	sleep_for=$(calc "$interval - ($after-$before) / 1000000000")
	sleep_for="$(echo $sleep_for | tr -d '\t')"
	#echo ${sleep_for:0:1}

	if [ "${sleep_for:0:1}" = "-" ]; then
		sleep_for=0
	fi

        echo "Sleep: $sleep_for"

	sleep $sleep_for
	((i++))
	if [ $i -gt $((len-1+4)) ]; then
		i=0
	fi
done
